---

# - hosts: all
- hosts:
    - backendonecab-w3
    - backendonecab-w2
  tags: ['config_node']
  roles:
    # - apt
    # - node_config_common
    # - master_config
    # - worker_config
    # - cicd_config
    - mount_partition
  vars_files:
    - vars.yaml
  gather_facts: true

- hosts:
    - backendonecab-m1
    - backendonecab-m2
    - backendonecab-m3
    - backendonecab-cn
  tags: ['config_kubectl']
  roles:
    # - postflight
  vars_files:
    - vars.yaml
  gather_facts: true

- hosts: all
  tags: ['config_registry']
  roles:
    - config-private-registry
  gather_facts: true


# - hosts: 
#     - backendonecab-w1
#     - backendonecab-w2
#     - backendonecab-w3
#     - backendonecab-cn
#   tags: ['config_nfs']
#   vars_files:
#     - vars.yaml
#   roles:
#     - nfs_server_config
#   gather_facts: true

