---

- hosts: all
  tags: ['config_node']
  roles:
    - apt
    - node_config_common
    - master_config
    - worker_config
    - cicd_config
    - mount_partition
  vars_files:
    - vars.yaml
  gather_facts: true

- hosts:
    - master1
  tags: ['config_kubectl']
  roles:
    - postflight
  vars_files:
    - vars.yaml
  gather_facts: true