# - name: Check if the ext4 filesystem already exists
#   stat:
#     path: "{{ partition }}"
#   register: partition_stat
#   ignore_errors: yes

- name: Create a ext4 filesystem on {{ partition }} and check disk blocks
  community.general.filesystem:
    fstype: "{{ filesystem }}"
    dev: "{{ partition }}"
    opts: -cc
    force: yes
  # when: partition_stat.stat.exists == False

- name: Ensure the longhorn mount point directory exists
  file:
    path: "{{ longhorn_mount_point }}"
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['kubenode']

- name: Check if the partition is already mounted at the longhorn mount point
  stat:
    path: "{{ longhorn_mount_point }}"
  register: mount_stat
  ignore_errors: yes

- name: Mount the partition longhorn
  mount:
    path: "{{ longhorn_mount_point }}"
    src: "{{ partition }}"
    fstype: "{{ filesystem }}"
    state: mounted
    opts: defaults
  when: inventory_hostname in groups['kubenode'] and mount_stat.stat.exists == True

- name: Ensure the nfs mount point directory exists
  file:
    path: "{{ nfs_mount_point }}"
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['cicd']

- name: Check if the partition is already mounted at the nfs mount point
  stat:
    path: "{{ nfs_mount_point }}"
  register: nfs_mount_stat
  ignore_errors: yes

- name: Mount the partition nfs
  mount:
    path: "{{ nfs_mount_point }}"
    src: "{{ partition }}"
    fstype: "{{ filesystem }}"
    state: mounted
    opts: defaults
  when: inventory_hostname in groups['cicd'] and nfs_mount_stat.stat.exists == True
