- name: Check if the ext4 filesystem already exists
  become: yes
  stat:
    path: "{{ longhorn_config.partition }}"
  register: partition_stat
  ignore_errors: yes

- name: Create a ext4 filesystem on {{ partition }} and check disk blocks
  become: yes
  community.general.filesystem:
    fstype: "{{ longhorn_config.filesystem }}"
    dev: "{{ longhorn_config.partition }}"
    opts: -cc
    force: yes
  # when: partition_stat.stat.exists == False
  when: inventory_hostname in groups['kubeworker']

- name: Ensure the longhorn mount point directory exists
  become: yes
  file:
    path: "{{ longhorn_config.mount_point }}"
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['kubeworker']

- name: Check if the partition is already mounted at the longhorn mount point
  become: yes
  stat:
    path: "{{ longhorn_config.mount_point }}"
  register: mount_stat
  ignore_errors: yes

- name: Mount the partition longhorn
  become: yes
  mount:
    path: "{{ longhorn_config.mount_point }}"
    src: "{{ longhorn_config.partition }}"
    fstype: "{{ longhorn_config.filesystem }}"
    state: mounted
    opts: defaults
  when: inventory_hostname in groups['kubeworker'] and mount_stat.stat.exists == True
