# - name: Check if the ext4 filesystem already exists
#   become: yes
#   stat:
#     path: "{{ partition }}"
#   register: partition_stat
#   ignore_errors: yes

- name: Create a ext4 filesystem on {{ partition }} and check disk blocks
  become: yes
  community.general.filesystem:
    fstype: "{{ filesystem }}"
    dev: "{{ partition }}"
    opts: -cc
    force: yes
  # when: partition_stat.stat.exists == False
  when: inventory_hostname in groups['kubeworker']

- name: Ensure the longhorn mount point directory exists
  become: yes
  file:
    path: "{{ longhorn_mount_point }}"
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['kubeworker']

- name: Check if the partition is already mounted at the longhorn mount point
  become: yes
  stat:
    path: "{{ longhorn_mount_point }}"
  register: mount_stat
  ignore_errors: yes

- name: Mount the partition longhorn
  become: yes
  mount:
    path: "{{ longhorn_mount_point }}"
    src: "{{ partition }}"
    fstype: "{{ filesystem }}"
    state: mounted
    opts: defaults
  when: inventory_hostname in groups['kubeworker'] and mount_stat.stat.exists == True

# - name: Ensure the nfs mount point directory exists
#   become: yes
#   file:
#     path: "{{ nfs_mount_point }}"
#     state: directory
#     mode: '0755'
#   when: inventory_hostname in groups['cicd']

# - name: Check if the partition is already mounted at the nfs mount point
#   become: yes
#   stat:
#     path: "{{ nfs_mount_point }}"
#   register: nfs_mount_stat
#   ignore_errors: yes

# - name: Mount the partition nfs
#   become: yes
#   mount:
#     path: "{{ nfs_mount_point }}"
#     src: "{{ partition }}"
#     fstype: "{{ filesystem }}"
#     state: mounted
#     opts: defaults
#   when: inventory_hostname in groups['cicd'] and nfs_mount_stat.stat.exists == True
