---

- block:
    - name: Add sudo permissions to the {{ master_node_username }}
      become: yes
      lineinfile:
        path: /etc/sudoers
        insertbefore: '^%sudo'
        line: '{{ master_node_username }} ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Allow ports for master node
      become: yes
      ufw:
        state: enabled
        rule: allow
        to_port: '{{ item }}'
      loop: "{{ master_node_allowed_ports }}"
      loop_control:
        loop_var: item
      when: disable_firewall==false

    - name: generate SSH key "{{ ssh_key_filename }}"
      become_user: "{{ master_node_username }}"
      user:
        name: "{{ master_node_username }}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: /home/{{ master_node_username }}/.ssh/{{ ssh_key_filename }}
        force: yes
  when: inventory_hostname in groups['kubemaster']